airline/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("fligths/",include('flights.urls',namespace='flights')),
    path("",include("users.urls"))
]

flights/urls.py
from django.urls import path
from . import views

app_name='flights'
urlpatterns=[

    path("index",views.index,name="index"),
    path("<int:flight_id>",views.flight,name="fligth"),
    path("<int:flight_id>/book",views.book ,name="book")

]

users/urls.py
from django.urls import path
from . import views
app_name='users'
urlpatterns = [
    path("index",views.index,name="index"),
    path("",views.login_view,name="login"),
    path("logout",views.logout_view,name="logout"),
    path ("sign_up",views.sign_up,name="sign_up")
    
]

flights/models.py
from django.db import models

# Create your models here.

class Airport(models.Model):
    code=models.CharField(max_length=4)
    city=models.CharField(max_length=64)
    def __str__(self) -> str:
        return f'{self.city}  ({self.code})'
  
class Flight(models.Model):
    origin=models.ForeignKey (Airport ,on_delete=models.CASCADE,related_name="departures")
    destination=models.ForeignKey(Airport,on_delete=models.CASCADE,related_name="arrivals")
    duration=models.IntegerField()
    
    
    def __str__(self) -> str:
        return  f"{self.id} :{self.origin} to {self.destination}"

class Passenger(models.Model):
    first=models.CharField (max_length=50)
    last=models.CharField( max_length=50)
    flights=models.ManyToManyField(Flight, blank=True,related_name="passengers")

    def __str__(self):
        return f"{self.first} {self.last}"

   

users/models.py
from django.db import models

# Create your models here.

flights/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from  .models import Flight ,Airport,Passenger

# Create your views here.
def index(request):

    flights= Flight.objects.all()
    context={"Flights":flights}

    return render (request,"fligths/index.html",context)

def  flight(request,flight_id):
    flight=Flight.objects.get(pk=flight_id)
    passengers=flight.passengers.all()
    context={"fligth":flight,"passengers":passengers,"non_passengers":Passenger.objects.exclude(flights=flight).all()}
    return render (request,"fligths/flight.html",context)

def book(request,flight_id):
    if request.method=="POST":
        flight=Flight.objects.get(pk=flight_id)
        passenger=Passenger.objects.get(pk=int(request.POST["passenger"]))
        passenger.flights.add(flight)
        return HttpResponseRedirect(reverse('fligth',args=(flight.id,)))
        

users/views.py
from django.shortcuts import render ,redirect
from django.contrib import messages
from django.contrib.auth.models import User
from flights .models import Passenger


from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate ,login ,logout 

# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
    
    return render(request,"users/user.html")







def login_view(request):
   if request.method=="POST":
       username=request.POST["name"]
       password=request.POST["password1"]
       user =authenticate(request,username=username,password=password)
       print (user)
       if user is not None:
           login(request,user)
           return HttpResponseRedirect(reverse("users:index"))
       else :
          return render(request,"users/login.html",{"message":"invalid data."})      

   return render(request,'users/login.html')



def logout_view(request):
    logout(request)
    return render(request,"users/login.html",{"message":"you'r logged out "})



def sign_up(request):
     if request.method == 'POST':
        username = request.POST['fname']
        lastname = request.POST['lname']

        email = request.POST['email']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        if username=='' or email==''or password1==''or password2=='':
            messages.info(request, 'Requierd Fields')
            return redirect('/users/sign_up/')
        if password1==password2:
            if User.objects.filter(email=email).exists():
                messages.info(request, 'Email Taken')
                return redirect('/users/sign_up/')
            elif User.objects.filter(username=username).exists():
                messages.info(request, 'Username Taken')
                return redirect('/users/sign_up/')
            else:
                 user = User.objects.create_user(username=username, email=email, password=password1,first_name=username, last_name=lastname)
                 user.save() 
                 print ("dddddddd")
                 user_model=User.objects.get(username=username)
                 new_passenger = Passenger.objects.create(first=user_model.first_name,last=user_model.last_name)
                 new_passenger .save()
                 messages.success(request, 'Thanks to join')

                 return redirect('')
     else:  
              return render(request,'users/sign_up.html')    

flights/templates/fligths/flight.html
{% extends 'fligths/layout.html' %}
{% block content %}
<h1>{{fligth.id}}</h1>
<ul>
    <li>Origin : {{fligth.origin}}</li>
    <li>Destination :{{fligth.destination}}</li>
    <li> Duration : {{fligth.duration}}</li>
</ul>
<h2>Passengers</h2>
<ul>
{% for passenger in passengers  %}
<li>{{passenger}}</li>
{% empty %}
<li>No Passengers</li>
    
{% endfor %}
</ul>
<h2>Add passenger</h2>
<form action="{% url 'flights:book' fligth.id %}" method="post">
 {% csrf_token %}
 <select name="passenger" id="">
    
    {% for passenger  in non_passengers %}
    <option value="{{passenger.id}}">{{passenger}}</option>
        
    {% endfor %}
        
 </select>
 <input type="submit">


</form>
<a href="{% url 'flights:index' %}">Back To fligths list</a>

    

{% endblock content %}

flights/templates/fligths/index.html
{% extends 'fligths/layout.html' %}
{% block content %}
<h1>Flights</h1>
<ul>
{% for f in Flights %}
<li>
    <a href="{% url 'flights:fligth' f.id %}">

    Flight {{f.id}}: {{f.origin}} To {{f.destination}}</a>
</li>


{% endfor %}



</ul>

{% endblock content %}

flights/templates/fligths/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
 {% block content  %}

 
 {% endblock  %}
</body>
</html>

users/templates/users/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Users</title>
</head>
<body>
    {% block body %}
    
    {% endblock body %}

    
</body>
</html>

users/templates/users/login.html
{% extends 'users/layout.html' %}

{% block body %}

{% if message %}
<div>{{message}}</div>
    
{% endif %}
    

<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}

    <input type="text" name="name" placeholder="UserName">
    <input type="password" name="password1" placeholder="Password">
    <input type="submit" value="Login">
</form>
<a href="{% url 'users:sign_up'  %} ">Sign Up</a>


{% endblock body %}

users/templates/users/user.html
{% extends 'users/layout.html' %}

{% block body %}
    <h1>Welcome {{request.user}}</h1>
    <a href="{% url 'users:logout' %}">logout</a>
    <br>
    <br>
   

    <a  href="{% url 'flights:index' %}">index</a>
{% endblock body %}
    